### ISSUE TITLE
Infinite loop when using short hand query + fragment

### ISSUE THREAD

**Issue by cecton** [apollographql/apollo-rs#101]
## Description

Infinite loop when using short hand query + fragment

### Steps to reproduce

When parsing this query: `{...stuff} fragment stuff on Stuff {foo}`

The parser loops indefinitely.

But it work without using the shorthand query: `query {...stuff} fragment stuff on Stuff {foo}`

### Expected result

Not loop indefinitely.

### Actual result

Loop indefinitely

### Environment

- Operating system and version:
- Shell (bash/zsh/powershell):
- `apollo-rs` crate: 3a63a187bf031a71d110775bffc590595aa30aab
- Crate version:

**Comment by lrlna** [comment]
taking a look!

**Comment by lrlna** [comment]
@cecton fixed on `main` for ya!
