### ISSUE TITLE
Parsing completely invalid input results in OOM failure

### ISSUE THREAD

**Issue by garypen** [apollographql/apollo-rs#104]
## Description

Attempting to parse completely invalid input results in OOM crash as parser eats all my memory

### Steps to reproduce

Trying to parse nonsense input:

```
    let parser = Parser::new("dtzt7777777777t7777777777z7");
    let ast = parser.parse();
    assert!(!ast.errors().is_empty());
```

### Expected result

This should fail as follows:

```
    let parser = Parser::new("dtzt7777777777t7777777777z7");
    let ast = parser.parse();
    assert!(!ast.errors().is_empty());
```

### Actual result

loops indefinitely until system runs out of memory.

### Environment

- Operating system and version: ubuntu 20.04
- Shell (bash/zsh/powershell): bash
- `apollo-rs` crate: github source main branch, commit: 14bb84337a8bacd5cd27d7d7df429936f104b63b
- Crate version: source

### Triage
I did some digging and I think the fix is something like this:
```
diff --git a/crates/apollo-parser/src/parser/grammar/document.rs b/crates/apollo-parser/src/parser/grammar/document.rs
index 6f32238..3623fd7 100644
--- a/crates/apollo-parser/src/parser/grammar/document.rs
+++ b/crates/apollo-parser/src/parser/grammar/document.rs
@@ -29,6 +29,9 @@ pub(crate) fn document(p: &mut Parser) {
             }
             _ => break,
         }
+        if !p.errors.is_empty() {
+            break;
+        }
     }

     doc.finish_node();
```
The problem is caused by the fact that the document() fn keeps getting the same node and doesn't react to the fact that the select_definition() fn has reported an error. It might also be a good idea to check that p.errors.is_empty() before starting to loop.

**Comment by lrlna** [comment]
Ah! Good catch @garypen, thanks!

What was happening is that our parser's error creation did not consume the current token that had the error, leading to there always being a token to parse. I've fixed this in #105.

We cannot run `p.errors.is_empty`, as a design goal for the parser is to be error resilient, i.e. continue parsing even if errors are encountered. We return the AST alongside an error vector if there are any errors.
