### ISSUE TITLE
optimising peek_n

### ISSUE THREAD

**Issue by Geal** [apollographql/apollo-rs#108]
We found in the router that we're spending a lot of time in the `Parser::peek_n` function, mainly because it is allocating a list of nodes before selecting only one of them: https://github.com/apollographql/router/issues/100

Could this be optimized to remove allocations? I can take care of it if you want

**Comment by lrlna** [comment]
`peek_n` and `peek_n_data` were not put together with much performance in mind, so feel free to optimise!
