### ISSUE TITLE
apollo-parser: allocation considerations when creating Tokens

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#117]
## Description

We currently allocate a new String for input chars when creating tokens in the lexer. While this is easy to follow/read and create errors with, this allocates every time. A consideration for a future refactor could be either to store the index into the input str, hold a slice of the input str, or something entirely different. Because the parser's `SyntaxKind` don't point back to `TokenKind`s created by the lexer, moving away from allocating for every token does not impact the syntax tree creation.

This will be useful for the Router's apollographql/router#100

**Comment by goto-bus-stop** [comment]
`apollo_parser::lexer::Token`s now hold a slice 🥳
