### ISSUE TITLE
Ast errors: return an iterator

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/apollo-rs#119]
Follow up to [this comment](https://github.com/apollographql/router/pull/136#discussion_r756083538) we might want ast.errors() to return an Iterator.

@lrlna Since the current errors() method takes self by reference, I'll probably go with an `Iterator` and not an `IntoIterator`, what do you think ? :)

**Comment by lrlna** [comment]
yea definitely an `Iterator` so we can have a return type of `Iter<'_>` of sorts would be good!
