### ISSUE TITLE
Rust GQL Client

### ISSUE THREAD

**Issue by mattoni** [apollographql/apollo-rs#121]
Hi there,

I wasn't sure if this is the right place, but I was wondering if Apollo plans to release a Rust client much like their Javascript/Swift ones, or if that's something they plan to leave up to the community. I've been looking for a solution and haven't been able to find one yet.

Thanks!

**Comment by lrlna** [comment]
Hi @mattoni. There are no plans at the moment for Apollo to write a Rust client, but never say never! 

If you're looking for a rust-based graphql client, there is the [graphql_client](https://docs.rs/graphql_client/latest/graphql_client/) project.
