### ISSUE TITLE
Improve usabilities

### ISSUE THREAD

**Issue by Danue1** [apollographql/apollo-rs#132]
[ref](https://github.com/apollographql/apollo-rs/pull/130)

I will sequentially PR the following contents one by one each time they are merged.
This is to break it down into smaller chunks to facilitate the review.

- [ ] Changed String to &str.
- [ ] Add Builder for each SDL.
- [ ] Improved test code readability.

**Comment by goto-bus-stop** [comment]
It looks like this issue was about apollo-encoder, which we've removed and replaced by serialization in apollo-compiler 1.0, so I'll close it!
