### ISSUE TITLE
Normalising queries

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#145]
## Context

The Router team is looking for an ergonomic way to normalise GraphQL queries after they have been parsed. I am not entirely sure yet how this puzzle piece will fit in the apollo-rs design, so this issue is to track and discuss requirement details. Some of the requirements for the moment include:
- omitting unused values: which removes operations and fragments that aren't going to be used when executing
- normalising literals: which replaces all numeric and string literals as well as list and object input values with "empty" values
- removing aliases, which removes field aliasing from the query
- sorting the AST

A couple of questions to think about when coming up with the design:
- should "normalisation" be opt-in?
- should it happen as part of semantic analysis?
- should this wait to be done as part of execution work?
- are all of the requirements generic enough to be available for all users of apollo-rs, or are they only Router specific.

One thing that is clear is that this work will be a lot easier to do on top of the Source Database that we will introduce with #144. 

### Prior art
The requirements above is what the [apollo-server](https://github.com/apollographql/apollo-server/blob/e468367d52e11f3127597e4fe920eb8294538289/packages/apollo-server-core/src/plugin/usageReporting/defaultUsageReportingSignature.ts) does when normalising queries for usage reporting

**Comment by goto-bus-stop** [comment]
This looks like it's about operation signatures, now tracked here: https://github.com/apollographql/federation-next/issues/26

I think that will be part of federation rather than apollo-rs so will close this issue
