### ISSUE TITLE
QUESTION: Modifying a parsed query

### ISSUE THREAD

**Issue by kpeters-cbsi** [apollographql/apollo-rs#171]
## Description

Suppose I have the query:
```
{ 
  myQuery {
    id
    foo {
      alpha
      beta
   }
}
```

And I wanted to *extract* the field `foo` from it, creating two queries:

```
{ 
  myQuery {
    id
}
```

and

```
{ 
  myQuery {
    foo {
      alpha
      beta
   }
}
```

Is there any way to partition the query like that, perhaps using `rowan`, or would that be something I'd have to develop myself?

**Comment by lrlna** [comment]
@kpeters-cbsi this is an _excellent_ question! Do you want to have two separate `String` type queries or two separate fully-typed ASTs as the end goal?

**Comment by lrlna** [comment]
@kpeters-cbsi If you don't need ASTs, it's a bit easier, and is something you can do without needing to hook into `rowan`. You can use `apollo-encoder` crate to create a `String` of a GraphQL Document as you walk down the AST and pull out the useful information you need for your two separate queries. I wrote up [an example here](https://gist.github.com/lrlna/2ce2cbac2452c0ce6a2ee5bf44aa6d18) of how you can do for the two queries you provided in your original question.

The work we are doing at the moment - using `salsa` crate to create an API to the context of an AST as well as perform semantic analysis - will make it easy to be able to create two ASTs out of something like this. It will also simplify some of the code in that example that annoyingly makes you loop a couple of times to get to a field's selection set. This is all to say -- user experience will improve shortly!
