### ISSUE TITLE
Create a rust-toolchain.toml file to fix the rust version for everyone

### ISSUE THREAD

**Issue by bnjjj** [apollographql/apollo-rs#183]
Following this PR #182 I had an issue caused by the new rust release (1.59) which detects more lints. But if you're still using 1.58.1 locally for example you will have other lint errors. I suggest to implement the same behavior we did on the router https://github.com/apollographql/router/pull/554

**Comment by lrlna** [comment]
Since we haven't had the need for rust-toolchain file over the last two years, I think it's safe to close this for now until/if the need comes up.
