### ISSUE TITLE
apollo-parser: SchemaDefinition should support description

### ISSUE THREAD

**Issue by bnjjj** [apollographql/apollo-rs#185]
Regarding the spec of GraphQL, `SchemaDefinition` should support description in the parser https://spec.graphql.org/October2021/#sec-Schema

**Comment by lrlna** [comment]
Nice catch!!

The parsing was set up for it, but ungrammar is missing the `Description?` bit up front https://github.com/apollographql/apollo-rs/blob/963b3552deaf7ba3a7eb5a698a90f20d0fc08242/graphql.ungram#L159-L160

I think there is also a bug with DESCRIPTION node creation: https://github.com/apollographql/apollo-rs/blob/963b3552deaf7ba3a7eb5a698a90f20d0fc08242/crates/apollo-parser/src/parser/grammar/description.rs#L5-L10

DESCRIPTION should have a **node** STRING_VALUE (so we need to start a guard for it) that then bumps a STRING.
