### ISSUE TITLE
Feature: Publishing the 'rover' introspection code as a crate

### ISSUE THREAD

**Issue by d4h0** [apollographql/apollo-rs#206]
Hi,

I'm wondering if there is any chance Apollo would publish the [introspection code of 'rover'](https://github.com/apollographql/rover/blob/main/crates/rover-client/src/operations/graph/introspect/schema.rs) as a separate crate.

I'd like to download the GraphQL schema of a GraphQL API (which I don't own), and process it using `apollo.rs`. The problem is, that `apollo.rs` only understands the IDL format of a GraphQL schema, and that the GraphQL introspection endpoint only returns the `Introspection JSON Format`.

Because you already did all the hard work of converting the JSON representation to IDL, I'm wondering if that code can be published.

PS: Thanks for publishing what you already did – I'm pretty excited about the [items on the roadmap](https://github.com/apollographql/apollo-rs/blob/main/ROADMAP.md)!

**Comment by lrlna** [comment]
hey @d4h0, that's a good query. TL;DR is that I need to think about it a little bit and get back to you.

Introspection in Rover requires a client of sorts to be able to fetch incoming JSON. We are currently using `graphql-client` crate for fetching, but it's not an ideal match with the type system (see [these `ofType`](https://github.com/apollographql/rover/blob/main/crates/rover-client/src/operations/graph/introspect/schema.rs#L334-L337) workarounds). This would ideally be published with apollo-rs' client that's designed to work with `apollo-rs` parser/encoder/compiler, which is really quite far down on the list that it's not yet on the roadmap 🤔. Let me think if there something we can do and get back to you!

**Comment by d4h0** [comment]
Thanks for thinking about it, @lrlna :)

Currently, I'm just using the `rover` CLI directly – which isn't the end of the world in my case (using a JS introspection library I found, and pulling in node.js, would be much worse). 

However, I think, a native introspection crate would be a great addition for the Rust GraphQL ecosystem (which is why I proposed it), so thanks again for considering it :)

**Comment by lrlna** [comment]
hey @d4h0, it might be a bit of time before an introspection crate could be part of apollo-rs. The cleanest solution, imo, is to still publish it as part of a graphql client that is inline with our existing parser, and soon to be compiler. 

In the meantime, the folks working on Rover have abstracted out our introspection code [into its own crate](https://github.com/apollographql/rover/tree/main/crates/launchpad) which I think should be very helpful for your use case. It is not a published crate, so you'll have to add it to your cargo toml via git url.

**Comment by d4h0** [comment]
Thanks for the update, @lrlna, this is fantastic! :)

**Comment by SimonSapin** [comment]
Closing as we’re unlikely to publish the current iteration of this code. It relies on the apollo-encoder crate, which we removed in PR https://github.com/apollographql/apollo-rs/pull/754 since its functionality is now covered by version 1.0 of apollo-compiler. Instead we plan on making introspection client functionality part of apollo-compiler: https://github.com/apollographql/apollo-rs/issues/675
