### ISSUE TITLE
normalise compiler database with interned values

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#218]
At the moment, we are using uuids to establish relationships between various bits of the compiler context. This is fine for the moment as we reason about various parts of the context, but in the future we should consider interning values and using their intern ids as references. This won't be a 1 for 1 substitute with uuids, but should provide us with a more performant lookup and a normalised db.

**Comment by goto-bus-stop** [comment]
Since we no longer use salsa in 1.0, I'll close this as no longer relevant
