### ISSUE TITLE
lexer fails to lex string values with escaped characters

### ISSUE THREAD

**Issue by garypen** [apollographql/apollo-rs#227]
## Description

See apollographql/router#1065

### Steps to reproduce

It's difficult to reproduce in the router, but I wrote a program to demonstrate the issue in the parser.

```
fn main() {
    use apollo_parser::Parser;

    let input = r#"mutation {
            createStore(draft: {
              name: [{ locale: "en", value: "\"my store\"" }]
            }) {
              name(locale: "en")
            }
          }"#;
    let parser = Parser::new(input);
    let ast = parser.parse(); <- This will never return until memory exhausted.
}
```

### Expected result

If mutation is valid it should parse. If not, fail with error(s).

### Actual result

Never returns until memory exhausted.

### Environment

- Operating system and version: Mac OS X
- Shell (bash/zsh/powershell): zsh
- `apollo-rs` crate: apollo-parser
- Crate version: 0.2.5

**Comment by garypen** [comment]
Additional information. I dug into this a little bit and found that the error was manifesting here:
```
diff --git a/crates/apollo-parser/src/parser/grammar/value.rs b/crates/apollo-parser/src/parser/grammar/value.rs
index 667d668..ed12916 100644
--- a/crates/apollo-parser/src/parser/grammar/value.rs
+++ b/crates/apollo-parser/src/parser/grammar/value.rs
@@ -50,7 +50,10 @@ pub(crate) fn value(p: &mut Parser) {
         }
         Some(T!['[']) => list_value(p),
         Some(T!['{']) => object_value(p),
-        _ => p.err("expected a valid Value"),
+        _ => {
+            eprintln!("we expected a valid value, but got nonsense");
+            p.err_and_pop("expected a valid Value")
+        }
     }
 }
 /// See: https://spec.graphql.org/October2021/#EnumValue
```
We never seem to realise that we are out of errors. If I change `p.err()` to `p.err_and_pop()`, then it works for the example program, but hacking around with the input makes it fairly easy to crash the program.

**Comment by lrlna** [comment]
@garypen you can update to `apollo-parser@0.2.6` for a fix.
