### ISSUE TITLE
Multiple input files to ApolloCompiler

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/apollo-rs#277]
It's not uncommon for users to have multiple files to make up their final graphql schema. IDEs generally support this and probably Apollo Compiler should as well.

It could be argued that schemas should be merged into a single file before passing to the compiler, but this means that line and column number references will be largely useless.

I haven't investigated if it is possible to merge several ApolloCompiler instances yet, maybe this is an avenue to take.

**Comment by garypen** [comment]
I think this duplicates: #221

**Comment by BrynCooke** [comment]
Indeed, closing.

**Comment by lrlna** [comment]
@BrynCooke it's coming soon!
