### ISSUE TITLE
Configure dependencies for builds targeting WASM

### ISSUE THREAD

**Issue by allancalix** [apollographql/apollo-rs#288]
## Description
https://github.com/apollographql/apollo-rs/issues/217

While exploring the possibility of targeting WASM, it would be great if users of `apollo-compiler` could target WASM.

In using the crate in a `wasm-pack` context, I found the`"js"` feature in the UUID crate and updating the version. See https://github.com/apollographql/apollo-rs/pull/287 for what is required to support this.

**Comment by lrlna** [comment]
yes! definitely a great first step for supporting wasm

**Comment by abernix** [comment]
Was this resolved via https://github.com/apollographql/apollo-rs/pull/287?

**Comment by lrlna** [comment]
yep, you're right @abernix
