### ISSUE TITLE
(Official) Apollo Server in rust

### ISSUE THREAD

**Issue by dotjon0** [apollographql/apollo-rs#291]
Not sure where to route this question. We can see the Apollo team launching various graphQL related 'rust' repos - are there any plans to launch an 'official' Apollo Server (graphQL) in rust (i.e. by the Apollo team)?

**Comment by lrlna** [comment]
Hi @dotjon0! Thanks for asking, this is a good question. The TL;DR is there are no plans to have an official apollo rust server in the near future. 

The ever-so-slightly longer answer is that this was brought up internally a few times, but at the moment we haven't necessarily found a need for it in our own work, nor have a lot of our users asked for this - you're one of the first. This may change in the future if we see the need arise (never say never)!

With that said, if anyone reads this and is looking for an apollo rust server, you may use this issue to note down your interest.

**Comment by dotjon0** [comment]
The compute savings and memory safety security benefits of rust make a clear case for GraphQL in Rust... Maybe a collaboration with https://github.com/graphql-rust/juniper is an idea... We love Apollo Server, with rust involved this makes an incredible combination... Thanks for your feedback @lrlna
