### ISSUE TITLE
testing apollo-rs on completely gibberish graphql 

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#304]
We want to be able to test some wildly incorrect graphql input and ensure the parser, and the compiler, and any other tools that might use these two crates are error resilient and don't panic. It would be good to figure out a succinct way to either run `apollo-smith` in a completely chaotic graphql environment, or to have some sort of separate fuzzing. 

~ chaos ~ engineering ~

**Comment by goto-bus-stop** [comment]
Added in https://github.com/apollographql/apollo-rs/pull/828
