### ISSUE TITLE
validation: leaf field selection

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#307]
implement leaf field selection [spec](https://spec.graphql.org/October2021/#sec-Leaf-Field-Selections)

**Comment by yanns** [comment]
I've opened a PR to partially implement this validation: https://github.com/apollographql/apollo-rs/pull/464

**Comment by yanns** [comment]
I've opened a PR for this: https://github.com/apollographql/apollo-rs/pull/465

**Comment by lrlna** [comment]
thanks @yanns! I'll take a look

**Comment by lrlna** [comment]
closed by #465
