### ISSUE TITLE
Unexpected escape character on quoted directive input argument

### ISSUE THREAD

**Issue by abernix** [apollographql/apollo-rs#359]
## Description

When parsing the following bits with `apollo-parser`, an error is emitted suggesting that an "unexpected escaped character" was reached:

```graphql
directive @myDir( fmt: String = "YYYY-mm-DD\\THH:i:S") on FIELD
```

### Steps to reproduce

```
    let src = r#" directive @myDir( fmt: String = "YYYY-mm-DD\\THH:i:S") on FIELD"#;
    let parser = Parser::new(&src);
    let ast = parser.parse();
```

### Expected result

While this is a curious case, in which I question what the intention of the escaping is, I think it should parse [as is the case with `graphql-js`](https://astexplorer.net/#/gist/fcb664cfe0fdeeb232f9a01183aa62a4/5bac04c10e578e8d51385836f21052f3488f63ca), though I'm curious what the interpretation is.

### Actual result

```
error: unexpected escaped character
--> repo:0:34
 |
0 |  directive @myDir( fmt: String = "YYYY-mm-DD\\THH:i:S") on FIELD
 |                                  ^^^^^^^^^^^^^^^^^^^^^ unexpected escaped character
 |


error: expected a valid Value
--> repo:0:55
 |
0 |  directive @myDir( fmt: String = "YYYY-mm-DD\\THH:i:S") on FIELD
 |                                                       ^ expected a valid Value
 |
```

### Environment

- Operating system and version: macOS M1 with an OS flavor named after somewhere warm/cold/wild/dangerous in California.
- Shell (bash/zsh/powershell): zsh
- `apollo-rs` crate: `apollo-parser`
- Crate version: `0.3.1`

**Comment by lrlna** [comment]
ah, this is similar to #343 and should indeed be fixed. let us publish a new version with the fix.

**Comment by lrlna** [comment]
fixed in the new release of apollo-parser -  [`0.3.2`](https://github.com/apollographql/apollo-rs/releases/tag/apollo-parser%400.3.2)
