### ISSUE TITLE
Compiler perf: consider HashMap indices for “find by” queries

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/apollo-rs#363]
Currently `find_object_type_by_name` is implemented by iterating through all object types until a match is found:

https://github.com/apollographql/apollo-rs/blob/c99504406c669e394a53045bbf1f4233b59e4790/crates/apollo-compiler/src/database/document.rs#L156-L166

Many `find_*_by_*` methods follow the same pattern.

If there are many object types, finding them all by name would take O(n²) time. This could be brought down to O(n) if this query relied on a different queries that builds and caches a hashmap of all object types, with their names as keys. (In this case, `find_object_type_by_name` might even be better off not being a query at all since salsa’s caching would be redundant) `is_subtype` uses a similar pattern with `subtype_map`.

The tradeoff is additional cost building the index if it ends up not being useful, for example if there are many object types but only one of them is ever fetched by name.

**Comment by lrlna** [comment]
This is a good thing to consider!

a small note on `find_object_type_by_name` being cached - we can add an attribute that does not store this query in the cache with `#[salsa::transparent]`. still keep the nice interface, but don't waste our storage facilities if we really think we will never want to find the same object type ever again.

**Comment by SimonSapin** [comment]
This was done in https://github.com/apollographql/apollo-rs/pull/387 and https://github.com/apollographql/apollo-rs/pull/403

**Comment by SimonSapin** [comment]
`find_directives_by_name` is a filter iterator, effectively a linear scan. `IndexMap` is used for things where duplicate names are invalid.
