### ISSUE TITLE
helper method for introspection queries

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#396]
Would be useful to have a convenience method in the compiler to check if an executable definition is an introspection query (check if the first field is `__type`?).

I see it working something like this:
```rust
let query_input = r#"
query Op {
  __type(name: "User") {
    name
    fields {
      name
      type {
        name
      }
    }
  }
}
"#;

let mut compiler = ApolloCompiler::new();
let query_id = compiler.create_executable(query_input, "query.graphql");

let diagnostics = compiler.validate();
for diagnostic in &diagnostics {
    println!("{}", diagnostic);
}

let op = compiler.db.find_operation_by_name(query_id, String::from("Op"))
    .expect("getProduct query does not exist");
let is_introspection = op.is_introspection(); // return a bool
```

Is there any other useful information we can provide convenience methods for in introspection queries?

**Comment by jregistr** [comment]
This looks interesting. I'd like to open a CR for this. I was writing some notes on what an implementation of this would have and came up with a question. Should this helper consider fragments or inline fragments?

Actually, if we are, then how deep do we follow these fragments? I came up with this crazy bit of a scenario that I ran on [Star wars api] (https://studio.apollographql.com/public/star-wars-swapi/explorer?variant=current).

```graphql
query IntoSpectDeepFragments {
    ...onRootTrippy
}

fragment onRootTrippy on Root {
   ...onRooten
}


fragment onRooten on Root {
  ...onRooten2
}

fragment onRooten2 on Root {
   __type(name: "Root") {
    ...onType
  }
}

fragment onType on __Type {
  fields {
    name
  }
}
```

I think this could keep going, no?

**Comment by jregistr** [comment]
If we should only consider field selection and return false if the selection is an inline or fragment expansion, then I think implementation is pretty simple. I have a local draft of a sample version I could PR.

**Comment by lrlna** [comment]
@jregistr a PR is welcome!

The example you provided returns an introspection result, right? If so, I'd consider it to be an introspection query and should return `true` to this API method. So it's going to have to check recursively. It _likely_ can be done in the same way we get variables in a given selection set - we also check fields, inline fragments and fragments for variables just like you would check here for field name == `__type`.

**Comment by jregistr** [comment]
>The example you provided returns an introspection result, right?

It does actually, so yeah, I agree, it's a valid introspection query.

>It likely can be done in the same way we get variables in a given selection set 

I'll take a look at that as reference for the fragments since that looked liked the trickier of the 3 selection types.
