### ISSUE TITLE
Pre-computed type system as a compiler input

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/apollo-rs#406]
apollo-compiler recently gained the ability handle multiple inputs. Each input has a string to be parsed with apollo-parser, and is optionally limited to only type definitions or only executable definitions.

To work around the limitation of Salsa being `!Sync`, in apollo-router we’d like first parse a schema (type system definitions), pre-compute what we can about it, extract all of that into read-only data that can be shared through `Arc` with multiple threads, and have each thread be able to use this in apollo-compiler without reparsing. "Pre-computed type definitions" a.k.a. "pre-computed schema" would be an additional kind of input that can be provided to a new compiler. However this single input in the new compiler could reference multiple string inputs from the original compiler, so `FileId` handling needs to be aware of this so that diagnostics print the correct context.

# Option 1

A single compiler can have type definitions from any number of pre-computed inputs *and* any number of string inputs. This could be enabled by separating the concept of "source" from the concept of "input". API sketch:

```rust
struct SourceId(u64);
struct Source {
    filename: PathBuf,
    text: Arc<str>,
}

struct InputId(u64);
enum Input {
    Schema(SourceId),
    Query(SourceId),
    Document(SourceId),
    PrecomputedSchema(Arc<PrecomputedSchema>),
}

pub struct PrecomputedSchema {
    // Type definitions etc
    sources: IndexMap<SourceId, Source>
}

#[salsa::query_group(InputStorage)]
pub trait InputDatabase {
    #[salsa::input] fn input(&self, id: InputId) -> Input;
    #[salsa::input] fn source(&self, id: SourceId) -> Source;
```

# Option 2

In order to reduce complexity from the above, we introduce a limitation : if a compiler has a pre-computed schema input, that must be the only input with type system definitions. (In other words, all other inputs must be "query" inputs with only executable definitions). That way we don’t need IDs for pre-computed inputs (the one is either there or not) and can stick with a single `FileId` type. Internally, HIR-construction queries would effectively have two separate "modes".

This is sufficient for current apollo-router plans. Since pre-computing a niche feature to begin with, it’s unlikely many other people will run into this limitation.

**Comment by lrlna** [comment]
Thanks for writing this out! 

At the moment I only expect `apollo-router` and @lennyburdette plugin work to be using a pre-computed type system, so it seems wise to keep the scope of it as small as possible and make other considerations should more use cases come up. That is, having _either_ a pre-computed schema or schema str as input for compiler's schema is fine.
