### ISSUE TITLE
Validation: forbidden kind of definition for restricted inputs

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/apollo-rs#409]
When using `create_schema` or `update_schema`, the input string is expected not to contain any executable definition. Similarly with `create_executable` or `update_executable` with executable definitions.

If such misplaced definitions exist, the parser will happily create AST node for them, and HIR construction will happily ignore these nodes. Validation needs to actively looks for relevant AST nodes (if it doesn’t already).

**Comment by lrlna** [comment]
done in #535
