### ISSUE TITLE
validation: root operation type should be of Object Type

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#418]
from conversation in https://github.com/apollographql/apollo-rs/pull/415#issuecomment-1380047832

we should validate operation type to be of object type, for example:

```graphql
schema {
  query: SomeInputType
}

input SomeInputType {
  name: String
}

type ShouldBeTheQuery {
  name: String
}
```

**Comment by SimonSapin** [comment]
In apollo-router I wrote code like this:

```rust
            let root_operations: HashMap<_, _> = compiler
                .db
                .schema()
                .root_operation_type_definition()
                .iter()
                .filter(|def| def.loc().is_some()) // exclude implict operations
                .map(|def| {
                    (
                        def.operation_type().into(),
                        if let hir::Type::Named { name, .. } = def.named_type() {
                            name.clone()
                        } else {
                            unreachable!()
                        },
                    )
                })
                .collect();
```

It would be nice if this `unreachable` error case was already handled during HIR construction, similar for example to an object type definition lacking a name.

**Comment by lrlna** [comment]
you shouldn't have to write that code in the router, since even on the parser level root operation type definition cannot accept any other type other than NamedType, and an error gets created.

In any case, with #419, if we already encounter an error in the parser (i.e. the Type of root operation type definition's operation type is not a named type, `query: [NotANamedType!]`), it won't be added to the HIR.

**Comment by SimonSapin** [comment]
> if we already encounter an error in the parser (i.e. the Type of root operation type definition's operation type is not a named type, `query: [NotANamedType!]`), it won't be added to the HIR.

I think that’s an excellent reason for the `RootOperationTypeDefinition::named_type` method to return a `&Name` or `&str` instead of `&Type`. There’s no need to make callers pattern-match enum variants that will never be returned.
