### ISSUE TITLE
serde json implementation for compiler errors

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#423]
It'd be handy to have a `serde_json` output for compiler errors. For execution, it's necessary that the errors follow [the error serialisation spec](https://spec.graphql.org/October2021/#sec-Errors.Error-result-format). The compiler errors are a lot more verbose than those needed for execution, but we might want to make sure the necessary fields `message`, `locations`, `path` are there so we can transform this information for execution-specific errors.

**Comment by EverlastingBugstopper** [comment]
This would be great to have for WASM packages 👍🏼

**Comment by SimonSapin** [comment]
I believe this is fixed in https://github.com/apollographql/apollo-rs/pull/668
