### ISSUE TITLE
meta fields in compiler's context

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#439]
For field validation, especially for validation involving introspection field types, it'd be useful to figure out how we should add implicit fields to compiler's context. So far, implicit directives and scalars are added to the HIR as the HIR gets created. These type don't have an AST associated with them, so in validation we must check whether or not a directive or scalar node has a location before proceeding to create a diagnostic. Extending the same logic to other meta fields like introspection, means fields (`__typename`, `__type`, `__schema`) and types (`__Field`, `__InputValue` etc) now also exist in the context and have no AST or location information associated with them. This will make validation rule implementation a bit verbose. It would be good to figure out a nice, ergonomic way of dealing with this virtual/meta nodes.

I had this idea of having a virtual file that could have all introspection types, implicit directives and scalars, but I am not sure if this will end up being a lot more work than `Option<HirNodeLocation>`

**Comment by SimonSapin** [comment]
I ran into this trying to use `hir::Field::ty` instead of apollo-router’s own algorithm for resolving types in selections. A test has this query:

```graphql
      {
        __type(name: \"Bar\") {
          name
          fields {
            name
            type {
              name
            }
          }
        }
      }
```

Because apollo-compiler is not aware of `__type`, for its sub-fields `hir::Field::parent_obj` is `None`.

**Comment by yanns** [comment]
Let me know if it's related:
when using `ApolloCompiler` with an introspection query, `compiler.validate()` returns an error:

```
Error: cannot query `__schema` field
    ╭─[query.graphql:3:7]
    │
  3 │ ╭─▶       __schema {
    ┆ ┆   
 20 │ ├─▶       }
    │ │             
    │ ╰───────────── `__schema` field is not defined
    │     
    │     Help: `__schema` is not defined on `Query` type
────╯
```
I guess this is because those introspection fields are not known by `ApolloCompiler`.

**Comment by lrlna** [comment]
@yanns yep, that's the same issue!

**Comment by yanns** [comment]
@lrlna do you have a concrete idea on how to tackle this?
I'd be ready to try this out.

**Comment by lrlna** [comment]
@yanns yes, we've got a path forward in #489.
