### ISSUE TITLE
HIR APIs should implicitly account for type extensions

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/apollo-rs#468]
Consider these methods:

```rust
impl TypeDefinition {
    pub fn directives(&self) -> &[Directive] { .. }
    pub fn field(&self, name: &str) -> Option<&FieldDefinition> { .. }
}

impl SchemaDefinition {
    pub fn directives(&self) -> &[Directive] {
    pub fn root_operation_type_definition(&self) -> &[RootOperationTypeDefinition] { .. }
    pub fn query(&self, db: &dyn HirDatabase) -> Option<Arc<ObjectTypeDefinition>> { .. }
    pub fn mutation(&self, db: &dyn HirDatabase) -> Option<Arc<ObjectTypeDefinition>> { .. }
    pub fn subscription(&self, db: &dyn HirDatabase) -> Option<Arc<ObjectTypeDefinition>> { .. }
}

impl ObjectTypeDefinition {
    pub fn directives(&self) -> &[Directive] { .. }
    pub fn fields_definition(&self) -> &[FieldDefinition] { .. }
    pub fn field(&self, name: &str) -> Option<&FieldDefinition> { .. }
    pub fn implements_interfaces(&self) -> &[ImplementsInterface] { .. }
}

impl InterfaceTypeDefinition {
    pub fn directives(&self) -> &[Directive] { .. }
    pub fn fields_definition(&self) -> &[FieldDefinition] { .. }
    pub fn field(&self, name: &str) -> Option<&FieldDefinition> { .. }
    pub fn implements_interfaces(&self) -> &[ImplementsInterface] { .. }
}

impl ScalarTypeDefinition {
    pub fn directives(&self) -> &[Directive] { .. }
}

impl EnumTypeDefinition {
    pub fn directives(&self) -> &[Directive] { .. }
    pub fn enum_values_definition(&self) -> &[EnumValueDefinition] { .. }
}

impl UnionTypeDefinition {
    pub fn directives(&self) -> &[Directive] { .. }
    pub fn union_members(&self) -> &[UnionMember] { .. }
}

impl InputObjectTypeDefinition {
    pub fn directives(&self) -> &[Directive] { .. }
    pub fn input_fields_definition(&self) -> &[InputValueDefinition] { .. }
}
```

(The above is intended to be exhaustive.)

In apollo-compiler 0.6.0, they all ignore the presence of any type extension. Callers are expected to call respective `extensions()` methods separately. As a result, apollo-router has code like this in many places:

```rust
def.fields_definition()
    .iter()
    .chain(
        def.extensions()
            .iter()
            .flat_map(|ext| ext.fields_definition()),
    )
```

I propose that this functionality should not only be provided by apollo-compiler, it should be the "default" behavior of all these methods. For example if I’m looking for the fields of an object type, the API that’s easiest to reach for should account for extensions.

If there’s a use case for HIR users to find only fields/directives/etc from non-extension definitions, that could be a separate method with a longer (more specific) name. However I wonder if such use cases wouldn’t be better off traversing the AST instead of the HIR.

This could also be the opportunity to expose name-keyed `IndexMap`s instead of slices for:

* Fields
* Implemented interfaces
* Union members
* Enum values

… similar to type definitions themselves. (Not directives, since some of them are repeatable.) For example, replacing both `fields_definition()` and `field(name)`:

```rust
impl ObjectTypeDefinition {
    pub fn fields(&self) -> &IndexMap<String, FieldDefinition> { .. }
}
```
```[tasklist]

- [ ] https://github.com/apollographql/apollo-rs/pull/481
- [ ] https://github.com/apollographql/apollo-rs/pull/482
- [ ] https://github.com/apollographql/apollo-rs/pull/484
- [ ] https://github.com/apollographql/apollo-rs/pull/486
```

**Comment by lrlna** [comment]
@SimonSapin we were just talking about this yesterday. It should be fine to account for extensions in HIR APIs, but we ought to still support just the original definition field/directive/etc getters. This would be less useful for the Router's use case, but very useful for linters/lsps/etc.

Using an IndexMap for some of the Field/ImplementedInterfaces/Variables could work too! I think it may have to be ~ `IndexMap<String, Option<FieldDefinition>>` sort of thing though. 

Did you want to give this implementation a go?

**Comment by SimonSapin** [comment]
I’d like to work on this but I’m not sure when.

Ok so keeping both with and without extensions could look like this:

```rust
impl ObjectTypeDefinition {
    /// All fields of this object type, whether defined either directly on this definition or on extensions
    pub fn fields(&self) -> &IndexMap<String, _> { .. }

    /// The fields of this object type definition.
    /// Does not include fields from extensions.
    pub fn self_fields(&self) -> &[_] { .. }
```

Similarly for directives, etc. Some questions:

* Why did you make map values an `Option`?
* Should items be cloned into the map, or wrapped in `Arc`?

**Comment by SimonSapin** [comment]
Since the ~only useful things to do with `&IndexMap` are iteration and lookup by key, we just agreed with Iryna not to expose it but instead have separate methods for those:

```rust
impl ObjectTypeDefinition {
    /// All fields of this object type, whether defined either directly on this definition or on extensions
    pub fn fields(&self) -> impl Iterator<Item = &FieldDefinition> + '_ { .. }

    /// Field a field by its name, whether defined either directly on this definition or on extensions
    pub fn field_by_name(&self) -> Option<&FieldDefinition> { .. }

    /// The fields of this object type definition, excluding those from extensions
    pub fn self_fields(&self) -> &[FieldDefinition] { .. }
}
```

This means the internal `IndexMap` can contain indices and doesn’t need to own clones or `Arc`s of `FieldDefinition`
