### ISSUE TITLE
resolving introspection queries

### ISSUE THREAD

**Issue by yanns** [apollographql/apollo-rs#469]
When having an `ApolloCompiler` with a schema, would it be possible to resolve an introspection query?
The `ApolloCompiler` has all information needed, no?

Is this is possible, is it a feature we should add to `apollo-compiler`? Or maybe to another crate using `apollo-compiler`?

**Comment by erikwrede** [comment]
@yanns In case the apollo team plans to push this back to the execution implementation (see Roadmap), I'd be interested in collaborate on that since my in-development python binding library could also make use of this. ☺️

**Comment by lrlna** [comment]
@yanns @erikwrede this is indeed scheduled to be implemented along with execution. It's a bit further down the immediate roadmap, and I am not entirely certain of the direction of our design (to the point where we don't even have an issue to track execution yet). I'll keep this issue open for introspection-specific resolving.

**Comment by zackangelo** [comment]
@yanns not sure what exactly your needs are but I started working on an executor on top of apollo-rs a few days ago that's capable of resolving introspection queries enough to power a graphiql UI: https://github.com/zackangelo/phoebus/tree/main/examples/http-axum

It's a bit messy and still missing some pretty big areas of the spec, though. Hope it helps.

**Comment by SimonSapin** [comment]
https://github.com/apollographql/apollo-rs/pull/645 has a draft implementation of introspection and execution.

At first, execution will likely be a private implementation detail of introspection. There is a large design space full of tradeoffs around how an execution engine (provided by a library) can interface with field resolvers (provided by library users), so this would need discussion with actual would-be users before we commit to a public API.

**Comment by yanns** [comment]
congrats for the first PR!
If you need feedback about some API, I'd be happy to test it with our use-cases.

**Comment by SimonSapin** [comment]
Yes, feedback as PR comments would be very welcome. Thanks!

`tests/doc_example.rs` in the PR shows an example of expected usage, to get you started.

**Comment by yanns** [comment]
I've tried to use it, but I first need to update other dependencies, and I have some issues I've put on discord: 
- https://discord.com/channels/1022972389463687228/1117957327216201758/1163481102049083483 (can found workaround)
- https://discord.com/channels/1022972389463687228/1117957327216201758/1163487327226712235

I don't know if it's interesting for you, or just noise :D

**Comment by SimonSapin** [comment]
Yes these are relevant but we’re not really on Discord for this project, please file futures on GitHub instead. I’ve created a Discord account to read these and filed https://github.com/apollographql/apollo-rs/issues/702 and https://github.com/apollographql/apollo-rs/issues/703. 

As to https://github.com/apollographql/apollo-rs/pull/645, it’s based on apollo-compiler 1.0 so yes you’ll likely need to start by using that version. It also provides [an AST](https://docs.rs/apollo-compiler/1.0.0-beta.4/apollo_compiler/ast/index.html) which may replace the need to use apollo-parser directly even if you need low-level to manipulation of syntax elements. If you don’t, hopefully [`apollo_compiler::Schema`](https://docs.rs/apollo-compiler/1.0.0-beta.4/apollo_compiler/schema/struct.Schema.html) and [`apollo_compiler::ExecutableDocument`](https://docs.rs/apollo-compiler/1.0.0-beta.4/apollo_compiler/executable/struct.ExecutableDocument.html) together should cover your needs. All three have `Display` and `.to_string()`, replacing the need for apollo-encoder.

**Comment by SimonSapin** [comment]
Fixed in https://github.com/apollographql/apollo-rs/pull/758
