### ISSUE TITLE
validation: scalar extension

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#475]
* [x] The named type must already be defined
* [x] the already defined type must be a Scalar type.
* [x] Any non-repeatable directives provided must not already apply to the original Scalar type.

[spec](https://spec.graphql.org/October2021/#sec-Scalar-Extensions.Type-Validation)

**Comment by goto-bus-stop** [comment]
we already have a test for the final bullet point: 
https://github.com/apollographql/apollo-rs/blob/2d4190cab2e955cc94c14d88838738e915791595/crates/apollo-compiler/test_data/diagnostics/0080_directive_is_unique_with_extensions.graphql#L6-L7

so this is complete!
