### ISSUE TITLE
HIR field_definition method returns None for all interface Fields

### ISSUE THREAD

**Issue by zackangelo** [apollographql/apollo-rs#498]
## Description

`field_definition` on HIR `Field` type does not work on interface fields. This seems to be because the method assumes the field is on an object (it uses `find_object_type_by_name`): 

https://github.com/apollographql/apollo-rs/blob/main/crates/apollo-compiler/src/database/hir.rs#L1382-L1388

Is this correct behavior? Should I be using another method to get the field definition for fields on interface types?

**Comment by lrlna** [comment]
ooooo that's certainly a bug!

this gets me thinking that `field.field_definition()` will only ever look at interfaces and object, as they are the only graphql types that have field definitions. types like scalars and unions don't, but could be the types that a particular field is referencing. so this `field_definition` method is a bit tricky!

**Comment by lrlna** [comment]
do you have an example of where this is not working with interfaces by the way? I'll add it explicitly to a test case

**Comment by zackangelo** [comment]
@lrlna went ahead and opened a PR with my fix and a test case 👆

**Comment by lrlna** [comment]
perrrrfect! thanks :)
