### ISSUE TITLE
reporting diagnostic with no colors

### ISSUE THREAD

**Issue by yanns** [apollographql/apollo-rs#499]
`apollo-compiler` is using [`ariadne`](https://github.com/apollographql/apollo-rs/blob/main/crates/apollo-compiler/Cargo.toml#L21) to report diagnostics.

Those reports are beautiful 🤩 , and colorful.
If someone wants to use those reports inside a log entry in json format, it'd be great to remove those color information:

<img width="1073" alt="Screenshot 2023-03-28 at 10 44 44" src="https://user-images.githubusercontent.com/51669/228181411-45455cc1-3b4a-4baf-879a-800c5c5c43ee.png">

It seems that enabling a crate feature might sufficient to support [`NO_COLOR`](https://no-color.org/):
- https://github.com/zesterer/ariadne#cargo-features
- https://crates.io/crates/concolor

WDYT of that?

**Comment by yanns** [comment]
> I am almost wondering if it'd rather be better to serialise `ApolloDiagnostic` before you write it to your logs, rather than using the `Display` impl? 

That's definitely an alternative that I'm considering.
I'm raising this ticket to discuss if we should tackle that on a more generic approach.

**Comment by lrlna** [comment]
gotcha! `auto-colour` feature of `ariadne` seems exactly what we need.

do you have any thoughts on this @goto-bus-stop? feel like ariadne in the compiler is your brain child :)

**Comment by goto-bus-stop** [comment]
I'm hoping to get on https://github.com/apollographql/apollo-rs/issues/617 very soon and we can address this easily then! It's also useful to have for finishing validation in the apollo router.
