### ISSUE TITLE
consider builder pattern API for creating compiler

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#513]
With the new limits in the compiler (#512), it'd be useful to consider adopting a builder pattern in the compiler. This would especially be handy, because three of our API methods currently panic if something else is set (parser limits panic if sources are already set, pre computed hir panics if another type system is set).

Something to consider when thinking about this is that currently setting a source returns its file id. Would this be a place to remove those file ids? is another way we can adopt a builder pattern and still return file ids?

**Comment by goto-bus-stop** [comment]
My initial thought was something like this:

```rust
let mut compiler = ApolloCompiler::builder()
  .token_limit(100_000)
  .recursion_limit(4_096)
  .build()
compiler.add_type_system(...)

let mut sub_compiler = ApolloCompiler::builder()
  .token_limit(100_000)
  .recursion_limit(4_096)
  .build_from_type_system(compiler.type_system());

sub_compiler.add_executable(...)
```

That would just be a fairly minimal change while keeping the existing sources APIs intact (including file IDs).

I agree this can be an opportunity to also rethink that API a bit with the experience from the router though 😇

**Comment by lrlna** [comment]
ooooo that looks like that could work with minimal changes!

i've been thinking a bunch about those file ids. i think it's a bit wonky in the router. plus i have a feeling there is something off with the way we use them for creating and updating files which is _perhaps_ causing those performance and usability issues in #461, #442 and #508. but those three are totally out of scope here ^__^

**Comment by SimonSapin** [comment]
apollo-compiler 1.0 no longer has compiler objects in the public API, but it has:

* A builder pattern for parser configuration. Can be skipped entirely when using the default config, e.g. `Schema::parse(text, filename)`
* A builder pattern for creating a schema from multiple input files

https://docs.rs/apollo-compiler/1.0.0-beta.1/apollo_compiler/struct.Parser.html
https://docs.rs/apollo-compiler/1.0.0-beta.1/apollo_compiler/schema/struct.SchemaBuilder.html
