### ISSUE TITLE
Indentation in apollo-encoder

### ISSUE THREAD

**Issue by goto-bus-stop** [apollographql/apollo-rs#539]
Currently nodes in apollo-encoder indent themselves when printing, which has awkward results in a few places. For example, input values are always indented with 4 spaces, which is correct for field arguments:
```graphql
type Object {
  field(
    "document the argument"
    argument: String!
  ): Int!
}
```
But not for directive arguments:
```graphql
directive @dir(
    "document the argument"
    argument: String!
  ) on FIELD
```

I think indentation should instead be passed down by parent nodes. We could semi-abuse the `.width()` format specifier for this,
```rust
write!("{description:indent$}", description = description, indent = 4)?;
```
It kinda makes sense, though technically the width specifier is meant to be used to pad (eg. if you provide 8 it will pad to 8 characters), which is a bit different.

Or we could have a separate function similar to `Display::fmt` that takes additional arguments for indentation and possible future formatting options, and then provide `Display` impls that call that internal function with default properties.

**Comment by lrlna** [comment]
i think there's been a few asks to allow users to set indentation as well.
```
write!("{description:indent$}", description = description, indent = 4)?;
```
^ `indent=4` would probably help there

**Comment by glasser** [comment]
It would also be nice to have a single-line format without indentation at all.

**Comment by SimonSapin** [comment]
apollo-compiler 1.0 has a new serializer that keeps track of current indent level internally, which fixes the original issue described here. Additionally, it support serializer configuration:

```rust
document.to_string() // default config: two-space indent. (Should it be four?)
document.serialize().indent_prefix("    ").to_string()
document.serialize().indent_prefix("\t").to_string()
document.serialize().no_ident().to_string() // single-line
```
https://docs.rs/apollo-compiler/1.0.0-beta.1/apollo_compiler/ast/struct.Serialize.html
