### ISSUE TITLE
Current design of returning fragment definitions by name prevents duplicate detection

### ISSUE THREAD

**Issue by allancalix** [apollographql/apollo-rs#545]
## Description
There are currently a number of validations applied to fragment definitions but the current implementation does not detect that each fragment for each name must be unique[^2]. It's not possible to add this validation to `validate_fragment_definitions`[^1] because fragment queries _all normalize definitions by name_.

I propose modifying `all_fragments` to return a flat `Arc<Vec<FragmentDefinition>` and rename the current implementation to `all_fragments_by_name`. The same should apply to the `fragments(file_id)` version of the methods.

[^1]: "https://github.com/apollographql/apollo-rs/blob/main/crates/apollo-compiler/src/validation/fragment.rs#L218"
[^2]: "https://spec.graphql.org/draft/#sec-Fragment-Name-Uniqueness.Formal-Specification"

**Comment by lrlna** [comment]
We do check for fragment duplicates here[^1]. We don't, however, do it specifically for fragments, it's all just kind of done in one go. We should probably split that up between executable validation and type system validation, so executable validation can be run in isolation. 

Here is an example with a duplicate fragment:
```graphql
type Query {
  pet: Pet
}

interface Pet {
  name: String!
}

type Dog implements Pet {
  name: String!
  barkVolume: Int
}

query UseAllFragments {
  pet {
    ... dogFragment
  }
}

fragment dogFragment on Dog {
  ... on Dog {
    barkVolume
  }
}

fragment dogFragment on Dog {
  ... on Dog {
    barkVolume
  }
}
```
and here is what the diagnostic looks like:
![image](https://user-images.githubusercontent.com/8107784/236418035-cc1597d8-bb02-4356-b06b-42fe29f19714.png)

[^1]: https://github.com/apollographql/apollo-rs/blob/main/crates/apollo-compiler/src/validation/validation_db.rs#L261

**Comment by SimonSapin** [comment]
Depending on "how raw" you want definitions, I think the AST may be more appropriate for some tasks. It can be accessed like this:

```rust
use apollo_compiler::database::AstDatabase;

// make a `compiler` and `file_id`

let ast = compiler.db.ast(file_id);
for def in ast.document().definitions() {
    // …
}

**Comment by lrlna** [comment]
I will close this issue, as we've redesigned the compiler with the `1.0.0-beta.x` releases and this shouldn't be an issue anymore. Feel free to reopen if something isn't right still.

**Comment by SimonSapin** [comment]
To expand a bit more on this, the 1.0 API is centered on high-level document [`Schema`](https://docs.rs/apollo-compiler/1.0.0-beta.10/apollo_compiler/schema/struct.Schema.html) and [`ExecutableDocument`](https://docs.rs/apollo-compiler/1.0.0-beta.10/apollo_compiler/executable/struct.ExecutableDocument.html) where `IndexMap` is usually used for things expected to have unique names in valid documents. Duplicates are detected during conversion (from AST) to this representation and then not preserved.

For use cases not satisfied by this, the lower-level [AST](https://docs.rs/apollo-compiler/1.0.0-beta.10/apollo_compiler/ast/index.html) is also provided. There, every collection is a `Vec` of items in the order they appear in GraphQL source text.
