### ISSUE TITLE
Add serialization to GraphQL to the new HIR

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#580]
as part of work to prepare for #420, it would be good to combine encoder type and compiler HIR types. This will make it easier to create a graphql document programmatically when needing to use the same document in the compiler.

One of the bigger considerations here is that `rover` depends on `apollo-encoder` when serialialising introspection JSON response. It'd be good for `rover` to continue to serialialise without needing to import the entire compiler create. Perhaps a crate, such `apollo-types`, might work?

**Comment by SimonSapin** [comment]
In apollo-compiler 1.0 ~everything is serializable with `Display` and `.to_string()`. This replaces the functionality of the apollo-encoder crate.
