### ISSUE TITLE
Unwanted inline fragment type condition inference

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/apollo-rs#584]
## Description

`hir::InlineFragment::type_condition` may return a type even if no type condition syntax was used.

### Steps to reproduce

```rust
    #[test]
    fn type_condition_is_not_inferred() {
        let mut compiler = ApolloCompiler::new();
        let input = r#"
            type Query {
                a: Int
            }
            { ... { a } }
        "#;
        let id = compiler.add_document(input, "");
        let op = compiler.db.find_operation(id, None).unwrap();
        let hir::Selection::InlineFragment(inline_fragment) = 
            &op.selection_set().selection()[0]
            else { panic!("expected inline fragment") };
        // the `on <name>` syntax was not used:
        assert_eq!(inline_fragment.type_condition(), None);
    }
}
```

### Expected result

`type_condition()` should return `None`, based on the absence of type condition syntax in the string input.

### Actual result

The HIR contains an inferred synthetic type condition based on type definitions in the input:

```rust
thread 'database::hir::tests::type_condition_is_not_inferred' panicked at 'assertion failed: `(left == right)`
  left: `Some("Query")`,
 right: `None`', crates/apollo-compiler/src/database/hir.rs:4422:9
```

The code responsible for this is:

https://github.com/apollographql/apollo-rs/blob/6a0b13f191cc77f0cfc76913e86b0a223f427d32/crates/apollo-compiler/src/database/hir_db.rs#L1576-L1579

### Context

In my opinion this behavior is undesirable. The information of what the original input looked like is lost, whereas the type inference information is already available through `InlineFragment::parent_type`.

Adding an (accurate) type condition that wasn’t there before is semantically correct, but my current use case involves serializing parts of a HIR back to GraphQL syntax with precise control of the generated strings. These strings are use as HashMap keys (to identify `@defer` sub-selections) and need to match exactly strings generated separately by TypeScript code inside the Router’s query planner.

**Comment by goto-bus-stop** [comment]
I think this makes sense. Just getting the string name of the "default" type if there is no type condition specified is not very useful information.

We can still retain the current behaviour for the `InlineFragment::type_def` method, where it looks up the type that the selection set *inside* the fragment is selecting against. (so it does automatically use the `parent_obj` value if the type condition is not set). That's useful to have to look up directives or do validation.
