### ISSUE TITLE
cargo fuzz for apollo-parser

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#59]
Once the test case generator in #114 is written we can use it to fuzz `apollo-parser`. `wasm-tools` also have a good [reference implementation](https://github.com/bytecodealliance/wasm-tools/tree/e67010a741b3e1686ec08ca80e517f8873fd9d4e/fuzz) that we could peek at when writing this. Writing a `fuzz_target` will be the smallest part of this task, the bulk of the work here would be to fix any bugs that we find when fuzzing.

**Comment by garypen** [comment]
I enabled some simple fuzz testing on the parser. I used a very small corpus of 1 schema and limited the input to alphanumeric:

schema
```
type Query {
  getAllBlogs(): [BlogPost]
  getBlogPost(id: ID!): BlogPost
}

type Mutation {
  addBlogPost(title: String!, content: String!, authorID: ID!): BlogPost!
}

type BlogPost {
  id: ID!
  title: String!
  content: String!
  hasAuthor: Author!
}

type Author {
  id: ID!
  name: String!
  hasBlog: [BlogPost]
}
```

Tiny code change:

```
use apollo_parser::Parser;

 fuzz_target!(|data: &[u8]| {
    if let Ok(v) = std::str::from_utf8(data) {
        if v.chars().all(|x| x.is_alphanumeric()) {
            let _ = Parser::new(v);
        }
    }
 });
```
Fuzzing is limited to +nightly, but it seems to be working fine. So far, it's been running for about 30 minutes and no issues found!

**Comment by Geal** [comment]
I think both the fuzzer and the test case generator are useful. The test case generator makes valid schemas and queries that we should handle correctly, while the fuzzer makes sure the parse is robust against the raw garbage that we can receive from network requests

**Comment by lrlna** [comment]
> I think both the fuzzer and the test case generator are useful. The test case generator makes valid schemas and queries that we should handle correctly, while the fuzzer makes sure the parse is robust against the raw garbage that we can receive from network requests

yep, that's why we want a fuzzer :)

**Comment by lrlna** [comment]
done with #168
