### ISSUE TITLE
Constructible / modifiable HIR

### ISSUE THREAD

**Issue by goto-bus-stop** [apollographql/apollo-rs#593]
Supersedes #590, and likely #580.

To unify the hir/encoder types, HIR types should be constructible. To modify documents (#420), the HIR is likely the nicest level to do it at (vs the low-level parser AST).

So the rough plan is:
- [ ] make the HIR nodes constructible (prob just add builders with `buildstructor`)
- [ ] have the whole HIR have one root node, so you can clone + modify a HIR
- [ ] add a serialization API to the HIR so you can use it instead of apollo-encoder
- [ ] add some basic modification methods for eg. adding fields or removing directives
- [ ] later integrate it with salsa possibly using a schema diff format??

**Comment by goto-bus-stop** [comment]
A pretty big issue i'm running into with having a single root node at the moment is that it more or less guarantees that there will be multiple Arcs pointing at the same definition nodes. That makes modifying them non-obvious, you can't just do `Arc::get_mut()` with multiple pointees and having a ton of mutexes in the hir seems quite bad/heavy weight.

**Comment by goto-bus-stop** [comment]
Our wording evolved a bit, so the issue is a bit outdated, should be merged with #526 or split in a different way. I'll keep it like this for now as we are still designing the higher level parts. Simon made a lot of progress on this branch: https://github.com/apollographql/apollo-rs/tree/mir

**Comment by SimonSapin** [comment]
I think we can consider this done, with the release of apollo-compiler 1.0 beta: https://docs.rs/apollo-compiler/1.0.0-beta.1/

**Comment by SimonSapin** [comment]
This was sort of a duplicate of https://github.com/apollographql/apollo-rs/issues/420
