### ISSUE TITLE
No parsing syntax error for variables in constant values

### ISSUE THREAD

**Issue by gmac** [apollographql/apollo-rs#595]
## Description

The following should produce a syntax error, as variables cannot be used in constant value positions:

```graphql
query($id1: ID, $id2: ID = $id1) {
  __typename
}
```

Apollo Compiler parses the above. By comparison, the `graphql-js` reference implementation produces the following parse error:

```
Syntax Error: Unexpected variable "$id1" in constant value.
```

### Steps to reproduce

Try parsing the above query.

### Expected result

Expected syntax error.

### Actual result

Apollo compiler successfully parses

**Comment by lrlna** [comment]
ah yep, that's a bug! thanks for reporting. I'll look into it next week.

this is a irl use case of issue reported in #538
