### ISSUE TITLE
add line and columnd number getters to ApolloDiagnostic

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#607]
We need line and column numbers for external, serde-json serialisable ApolloDiagnostics. `ariadne` does compute this information, but unfortunately does not expose it.

**Comment by SimonSapin** [comment]
Fixed in https://github.com/apollographql/apollo-rs/pull/668 (for 0.11) and https://github.com/apollographql/apollo-rs/pull/698 (for 1.0)
