### ISSUE TITLE
use existing encoder

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#61]
this may require some adjustments in the encoder's API

**Comment by Danue1** [comment]
As you can see from the recent PR, I am very interested in this project.
Looking at various contexts, it seems that SDL and AST need to be integrated. Do you have any specific plans?
If you give me a suitable job, I will do it if I can.

**Comment by Danue1** [comment]
About two years ago, I wrote [GraphQL Parser](https://github.com/Danue1/graphql-rs).
At the time, I used a Parser-Combinator called nom, but I think I have reached a level where I can parse without such a thing.

**Comment by lrlna** [comment]
Hi @Danue1, thanks so much for your interest! Apologies for the lacking issue description. I've written it for myself as a "todo item" a while back and never went back to correct it 

To elaborate on this issue a little bit: `apollo-encoder` and `apollo-parser` are still very much a work-in-progress. This issue was created to integrate `apollo-encoder` with the AST produced by the `apollo-parser`. There is still definitely a plan to integrate the parser and the encoder, but it will have to be implemented after the work that's currently happening with semantic analysis (a [very] brief description of the latter is in our [`ROADMAP.md`](https://github.com/apollographql/apollo-rs/blob/49e553c223fb28db21e5433c16bd756afa588a79/ROADMAP.md)). What I can say is that it's very likely that the encoder will actually be integrated with the semantic analyser that's built on top of the parser, rather than the parser itself. And the parser is likely going to have a much simpler From<SyntaxTree> for String implementation. 

As we are still hashing out the details on the design and architecture of the overall project, I am afraid I cannot accept external contributions. Smaller, non-breaking changes, like for example the more generic String parameters you proposed in one of your commits, or bug fixes are fine, but we will have to wait a little while longer to accept larger design changes. This is mostly because there are lots of things in flight, and I don't want to confuse external folks with very frequent changes we will be doing in the next couple of months. Hope you can understand!

**Comment by Danue1** [comment]
@lrlna 
Okay, I understand...

```rust
let sdl = Sdl::new(...);
let (ir, errors) = SemanticAnalyser::new(...).validate(&sdl)?;
```

I think the design will come out roughly like the pseudo code above.

I can't wait until the 1.0 release. I want to use this project right away.
I wish there was something I could do.
If nothing else... I'll just watch the progress.

**Comment by goto-bus-stop** [comment]
I believe this is obsolete now that apollo-compiler includes serialization
