### ISSUE TITLE
Apollo-rs capabilities

### ISSUE THREAD

**Issue by dwivedianurag** [apollographql/apollo-rs#615]
can we use apollo-rs to build a middleware for graphql 
can we get some extensive example of how to use apollo-rs for graphql
can we use apollo-rs  to validate(example for Fragment Name Uniqueness,
Fragment spread type existence) agains the schema  (the schema will be a response to the interospection query i.e. it will not be predefine

**Comment by goto-bus-stop** [comment]
I'm not sure what a middleware refers to in this case. apollo-rs implements the *language* GraphQL, it doesn't provide a server or client or something like that. You can use it to parse operations or schemas.

It does support validation. Today only schemas from GraphQL source text are supported, but we are currently working on a feature that will allow you to build a schema from other things (like introspection queries).
