### ISSUE TITLE
parser: 0.6.0 fails to lex block string comment

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#632]
The following lexed properly in `apollo-parser@0.5.3`:

```
"""
'/\W/'
"""
type Query {
  a: String
}
```

But now, on `apollo-parser@0.6.0` produces an error:

```
errors: ERROR@173:187 "unexpected escaped character" """
'/\W/'
"""
```
related apollographql/router#3680

**Comment by SimonSapin** [comment]
I think this is another case https://github.com/apollographql/apollo-rs/issues/609
