### ISSUE TITLE
Sort schema contents for serialization

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/apollo-rs#649]
# Background

GraphQL syntax has lots of cases where ordering as not meaningful. For example, reordering top-level definitions in a document does not change its semantics.

In some cases apollo-compiler relies on this to simplify high-level data structures. For example, `Schema` serializes all directives definitions before type definitions. In other case it avoids shuffling things arbitrarily (or worse, non-deterministically with `HashMap`’s default random hasher) by preserving insertion/parse order with `Vec` or `IndexMap`.

This is a good default but not always desired. For example in composition of multiple subgraph schemas into a supergraph schema, subgraphs are not inherently ordered so a supergraph serialization independent of subgraph processing order is preferable.

# Proposal

Add an opt-in way to obtain a sorted serialization of `Schema`. Either:

* A method of `Schema` that takes `&mut self` and sorts it in-place
* A config parameter for serialization that leave the `Schema` data structure untouched. (There already is a builder API for serialization config. Usage might look like: `schema.serialize().sorted().to_string()`)

To some extent, [what to sort exactly and how is a matter of opinion](https://github.com/graphql/graphql-js/issues/3971). A starting point could be [`lexicographicSortSchema`](https://github.com/graphql/graphql-js/blob/v16.8.1/src/utilities/lexicographicSortSchema.ts) in graphql-js

**Comment by abernix** [comment]
@dariuszkuc Can you open that as a separate issue?

**Comment by dariuszkuc** [comment]
It is related to printing but yeah created separate issue to track it -> https://github.com/apollographql/apollo-rs/issues/664

**Comment by dariuszkuc** [comment]
After looking into this a bit more it looks like subgraphs are composed in a alphabetical order (by their name) and while the resulting types in the schema are printed in order, their contents are not. Looks like we can close this issue as it is fairly easy to sort the types and directives in expected order.
