### ISSUE TITLE
directive built in types get added regardless of schema definitions

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#656]
First differential fuzzing bug, entirely unrelated to differential fuzzing!

Our built-in types get added regardless if a user-provided schema already has that built-in type defined. This is good for scalars - users cannot redefine built-in types. This is not the case for directives (iirc), so when a supergraph comes in with a defined `deprecated` definition, our built-in deprecated definition conflicts and results in "directive is already defined" validation error. We should only add built-in directives to the hir only if a schema doesn't already have them.

**Comment by SimonSapin** [comment]
> This is not the case for directives

This was surprising to me so I checked and found:

https://spec.graphql.org/October2021/#sec-Type-System.Directives.Built-in-Directives
> When representing a GraphQL schema using the type system definition language any built-in directive **may** be omitted for brevity.

(emphasis added)

Conversely, an SDL may contain definitions for built-in directives.

On the other hand:

https://spec.graphql.org/October2021/#sec-Schema
> All directives within a GraphQL schema must have unique names.

Reconciling the two is a bit weird but I think what we need to do is:

* When building a `Schema` or HIR, first add `built_in_types.graphql` like we already do
* Other files are allowed to override a built-in directive definition, but only once

In pseudo-code:

```rust
match new {
    // …
    ast::Definition::DirectiveDefinition(new_def) => {
        if let Some(old_def) = self.schema.directive_definitions.get(&new_def.name) {
            if old_def.is_built_in() { // old_def has file_id == FileId::BUILT_IN
        }
    }
}
```

**Comment by SimonSapin** [comment]
Fixes in https://github.com/apollographql/apollo-rs/pull/684 for the 1.0 branch
