### ISSUE TITLE
Add parsing + validation support for `FieldSet` scalars

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/apollo-rs#681]
Apollo Federation has multiple directives that take an argument of type [`FieldSet`](https://www.apollographql.com/docs/federation/subgraph-spec/#scalar-fieldset) to designate one or more fields of an object (or interface?) type. `FieldSet` is a custom scalar serialized as a string. Its value is expected to be parsed as a [`SelectionSet`](https://spec.graphql.org/October2021/#SelectionSet) with optional outer brackets. (This is GraphQL syntax inside of a string in GraphQL syntax.)

Currently apollo-rs can only parse GraphQL documents, but we’d rather Rust federation not need string concatenation hacks to create a parser input that looks like a document.

## API sketch

In apollo-parser:

* Give `apollo_parser::SyntaxTree` a `Cst` type parameter
* `apollo_parser::Parser::new(string).parse()` now returns `SyntaxTree<apollo_parser::cst::Document>` instead of just `SyntaxTree`
* Add `apollo_parser::Parser::new(string).parse_fieldset()` which returns `SyntaxTree<cst::SelectionSet>`
* The `SyntaxTree::document(self) -> cst::Document` method now only exists on `SyntaxTree<cst::Document>`
* Add `SyntaxTree::selection_set(self) -> cst::SelectionSet` for `SyntaxTree<cst::SelectionSet>`

In apollo-compiler:

* Add a top-level free function:
  ```rust
  fn parse_fieldset(
      schema: &Schema,
      type_name: impl Into<ast::NamedType>,
      source_text: impl Into<String>,
      path: impl AsRef<Path>,
  ) -> executable::SelectionSet
  ```
* Add a `Parser` method with the same signature

**Comment by SimonSapin** [comment]
Validation is also needed:
> could parse `query { __typename } fragment F on SomeObjectType { <insert FieldSet string here> }` […]

> in the case above with `FieldSet`, we’d like to skip the operation validation https://spec.graphql.org/draft/#sec-Fragments-Must-Be-Used 

I propose that:

* We add a `pub struct FieldSet(pub SelectionSet);` wrapper type in the `executable` module,
* `parse_fieldset` returns it instead of `SelectionSet`
* It has a `validate` method with the same signature as `ExecutableDocument::validate`
  - For compatibility with Salsa-based validation, this method may create a temporary `ast::Document` that looks like above
  - Eventually when they are migrated to not require Salsa, only call validation functions relevant to selection sets and skip creating a temporary document entirely

**Comment by lrlna** [comment]
I was thinking to go about slightly differently, which may simplify this design. I was hoping that `Parser::new(string).selection_set()` would return a `SyntaxNode` which could then be added to an existing `ExecutableDocument` that's currently getting modified. 

This would allow us to not have a special validation method for just the selection set - the `FieldSet` would be validated along with the executable document it will inserted into.

**Comment by SimonSapin** [comment]
Fixed in https://github.com/apollographql/apollo-rs/pull/685
