### ISSUE TITLE
Missing encoder release compatible with parser 0.7

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/apollo-rs#703]
From @yanns in https://discord.com/channels/1022972389463687228/1117957327216201758/1163487327226712235, via https://github.com/apollographql/apollo-rs/issues/469#issuecomment-1764646902:

> Another issue upgrading `apollo-parser` to 0.7.1 is the missing update for `apollo-encoder`:
> ```rust
> error[E0277]: the trait bound `apollo_encoder::SchemaDefinition: From<apollo_parser::cst::SchemaDefinition>` is not satisfied
>   --> src/feature_toggle/schema_transformation.rs:42:68
>    |
> 42 |             Definition::SchemaDefinition(e) => pub_schema.schema(e.try_into()?),
>    |                                                                    ^^^^^^^^ the trait `From<apollo_parser::cst::SchemaDefinition>` is not implemented for `apollo_encoder::SchemaDefinition`
>    |
>    = note: required for `apollo_parser::cst::SchemaDefinition` to implement `Into<apollo_encoder::SchemaDefinition>`
>    = note: required for `apollo_encoder::SchemaDefinition` to implement `TryFrom<apollo_parser::cst::SchemaDefinition>`
>    = note: required for `apollo_parser::cst::SchemaDefinition` to implement `TryInto<apollo_encoder::SchemaDefinition>`
> ```

**Comment by lrlna** [comment]
@yanns there is now `apollo-encoder@0.8.0`, compatible with parser 0.7.x. Sorry about this publishing mishap!

**Comment by yanns** [comment]
awesome thanks!
