### ISSUE TITLE
Names must not start with two underscores `__`

### ISSUE THREAD

**Issue by qwerdenkerXD** [apollographql/apollo-rs#743]
## Description

The [Specification](https://spec.graphql.org/October2021/#sec-Names.Reserved-Names) declares the following:
```md
# Reserved Names
Any Name within a GraphQL type system must not start with two underscores "__"
unless it is part of the introspection system as defined by this specification.
```
Currently, this is not satisfied by `apollo-compiler@1.0.0-beta.6` and has been forgotten in PR #713

### Steps to reproduce

Validate the following schema which has some of such invalid names defined:
```graphql
type Query {
  __field(__arg: __MyScalar!): __MyType!
}

type __MyType {}

interface __MyInterface {}

scalar __MyScalar

enum __MyEnum {
  __EnumValue
}

union __MyUnion = __MyType | __Schema

input __MyInput {
  __field: __MyScalar!
}
```
[Here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=use+apollo_compiler%3A%3ASchema%3B%0D%0A%0D%0Afn+main%28%29+%7B%0D%0A++++let+schema%3A+%26str+%3D+r%23%22%0D%0A++++++type+Query+%7B%0D%0A++++++++__field%28__arg%3A+__MyScalar%21%29%3A+__MyType%21%0D%0A++++++%7D%0D%0A%0D%0A++++++type+__MyType+%7B%7D%0D%0A%0D%0A++++++interface+__MyInterface+%7B%7D%0D%0A%0D%0A++++++scalar+__MyScalar%0D%0A%0D%0A++++++enum+__MyEnum+%7B%0D%0A++++++++__EnumValue%0D%0A++++++%7D%0D%0A%0D%0A++++++union+__MyUnion+%3D+__MyType+%7C+__Schema%0D%0A%0D%0A++++++input+__MyInput+%7B%0D%0A++++++++__field%3A+__MyScalar%21%0D%0A++++++%7D%0D%0A++++%22%23%3B%0D%0A%0D%0A++++let+schema+%3D+Schema%3A%3Aparse%28schema%2C+%22schema%22%29%3B%0D%0A%0D%0A++++assert%21%28schema.validate%28%29.is_err%28%29%2C+%22Expected+error+for+defining+Names+starting+with+%27__%27%22%29%3B%0D%0A%7D) a code sample.

### Expected result

The validation should fail and have some respective diagnostics.

### Actual result

The validation succeeds.

### Environment

- Operating system and version: Ubuntu 20.04.6 LTS
- Shell (bash/zsh/powershell): zsh
- `apollo-rs` crate: apollo-compiler
- Crate version: 1.0.0-beta.6

**Comment by goto-bus-stop** [comment]
`Name` also represents introspection names, so it's intentional that it supports underscores. We should handle this in validation, though!

**Comment by SimonSapin** [comment]
I think we could check this either:

* In various `.validate()` methods, under `if file_id != BUILT_IN` for introspection names. I believe so far we don’t have validation rules that need to find every single `Name`, so we’ll need to be careful not to miss some of them in various parts of data structures.
* When converting from CST to AST, under `if file_id != BUILT_IN`. This requires adding the ability for this conversion to emit parse errors. (Currently it relies on apollo-parser having emitted all relevant errors.)
* In apollo-parser’s lexer, with a new `allow_builtin_names` configuration

I have a mild preference for the lexer, since that’s where we check other aspects of `Name` syntax

**Comment by SimonSapin** [comment]
I wrote the above with the incorrect assumption that every single `Name` anywhere in a document would need checking. The spec phrasing isn’t great but I think the spirit of it is about *definitions* that introduce a new named thing in a type system. So yes, checking in `Schema::validation` makes more sense.

**Comment by qwerdenkerXD** [comment]
![spec-ref](https://github.com/apollographql/apollo-rs/assets/107982913/997cddd8-7abb-4530-86e3-636292f418f8)
sounds like everything to me. So including it in executables is also necessary.
But I agree to check only for _definitions_, as you aren't able to refer to such definitions anyway if you can't define them.

**Comment by SimonSapin** [comment]
The reserved name bit of spec does say "Any Name within a GraphQL type system" though. Type system being a schema. :thinking:
