### ISSUE TITLE
empty field definition list allowed for object type definition

### ISSUE THREAD

**Issue by qwerdenkerXD** [apollographql/apollo-rs#753]
## Description

As defined in [Specification](https://spec.graphql.org/October2021/#sec-Objects.Type-Validation) has an object type to define at least one field.
This is not satisfied in grammar of `apollo-parser`.

### Steps to reproduce

Validate this very simple schema:
```graphql
type Query {}
```
[Here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=use+apollo_parser%3A%3AParser%3B%0D%0A%0D%0Afn+main%28%29+%7B%0D%0A++++let+parser+%3D+Parser%3A%3Anew%28%22type+Query+%7B%7D%22%29%3B%0D%0A++++let+cst+%3D+parser.parse%28%29%3B%0D%0A%0D%0A++++assert%21%28cst.errors%28%29.len%28%29+%21%3D+0%2C+%22Expected+error+for+missing+field+definitions%22%29%3B%0D%0A%7D) a code sample.

### Expected result

The parsed syntax tree should have one error with the message:
`expected Field Definition`

### Actual result

No errors.

### Environment

- Operating system and version: Ubuntu 20.04.6 LTS
- Shell (bash/zsh/powershell): zsh
- `apollo-rs` crate: apollo-parser
- Crate version: 0.7.4

**Comment by qwerdenkerXD** [comment]
Maybe just do the same as for enum or input types, so instead of doing this
https://github.com/apollographql/apollo-rs/blob/208d2d7960459469891ff2ab5584f23d02a54d6d/crates/apollo-parser/src/parser/grammar/object.rs#L40-L42
just do sth. like
```rust
...

if let Some(T!['{']) = p.peek() {
   object_fields_definition(p);
}

...

pub(crate) fn object_fields_definition(p: &mut Parser) {
    let _g = p.start_node(SyntaxKind::FIELDS_DEFINITION);
    p.bump(S!['{']);
    if let Some(TokenKind::Name | TokenKind::StringValue) = p.peek() {
        field::field_definition(p);
    } else {
        p.err("expected Field Definition");
    }
    while let Some(TokenKind::Name | TokenKind::StringValue) = p.peek() {
        field::field_definition(p);
    }

    p.expect(T!['}'], S!['}']);
}
```

But at this point I'm wondering if there is any case where a list of definitions defined as e.g. here *FieldsDefinition*<sub>list</sub> is expected to possibly be empty. Because then it would need to be changed for the field grammar.
As you are more familiar with the GraphQL spec, you may know the answer, because I don't read it from the spec.

**Comment by SimonSapin** [comment]
I think you’re correct. In spec notation the "list" suffix is defined as "one or more": https://spec.graphql.org/October2021/#sec-Grammar-Notation.Optionality-and-Lists

There’s also "opt" for optional. On principle *Something*<sub>list opt</sub> could be used for "zero or more" but I didn’t find it used.

**Comment by SimonSapin** [comment]
I think you’re correct. In spec notation the "list" suffix is defined as "one or more": https://spec.graphql.org/October2021/#sec-Grammar-Notation.Optionality-and-Lists

There’s also "opt" for optional. *Something*<sub>list opt</sub> is used for "zero or more":

![image](https://github.com/apollographql/apollo-rs/assets/291359/1204da6c-6753-43ed-ae93-c1198d6677be)

**Comment by qwerdenkerXD** [comment]
Ok then it needs to be changed in field grammar. If I'm right, this issue also exists for extensions and would be fixed in this way.

**Comment by SimonSapin** [comment]
I believe this is fixed in https://github.com/apollographql/apollo-rs/pull/845 and https://github.com/apollographql/apollo-rs/pull/847.
