### ISSUE TITLE
`DirectiveList::into_iter` unexpectedly yields references

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/apollo-rs#821]
`DirectiveList::into_iter` unexpectedly yields references.
I'd expect a function name `into_iter` to iterate over owned values.

```
  let list = DirectiveList::new();
  list.into_iter().map(|d: &Node<Directive>| d  ) // &Node!
```
 
Standard Vec:   
```
  let list = vec![1, 2];
  list.into_iter().map(|d: i32| d  ); // Owned
```

**Comment by SimonSapin** [comment]
`DirectiveList` itself does not have `into_iter`, so in this example code the compiler implicitly adds a reference like `(&list).into_iter()` to call the trait impl for `&'_ DirectiveList`:

https://github.com/apollographql/apollo-rs/blob/0fa07a82734abcbbbb47ea1485e80e9aeb9e5a1a/crates/apollo-compiler/src/ast/impls.rs#L599-L607

This impl exists to make code like `for dir in &something.directives` work. We can add an owned `impl IntoIterator for DirectiveList` to make this example behave as expected.

In what kind of situation do you manipulate an owned `DirectiveList`?

**Comment by BrynCooke** [comment]
I hadn't realized that `into_iter` may yeild reference, owned or mut ref depending on context.

I think implementing `IntoIterator` would still be a nice thing, the exact usecase I don't remember as the code was a conversion of some `apollo-smith` logic that eventually got deleted anyway. It was just an unexpected surprise.
