### ISSUE TITLE
Validation: forbid __schema outside of the root type

### ISSUE THREAD

**Issue by Geal** [apollographql/apollo-rs#903]
According to @IvanGoncharov , `__schema` should not be used outside of the root type: https://github.com/apollographql/router/pull/5255#discussion_r1699109946

Do we check this somewhere?

**Comment by SimonSapin** [comment]
In a typical schema, non-root types don’t have a `__schema` field so converting AST to an `ExecutableDocument` would fail with a `BuildError::UndefinedField`. In code, meta-fields like `__schema` are not present in the Rust struct `ObjecType.fields` but are returned if you instead call [`schema.type_field(type_name, field_name)`](https://docs.rs/apollo-compiler/1.0.0-beta.20/apollo_compiler/schema/struct.Schema.html#method.type_field).

Defining a schema like `type Something { __schema: Int }` is [disallowed per spec](https://spec.graphql.org/draft/#sec-Names.Reserved-Names) but we don’t yet implement that validation rule: https://github.com/apollographql/apollo-rs/issues/743

**Comment by SimonSapin** [comment]
Closing as duplicate of https://github.com/apollographql/apollo-rs/issues/743
