### ISSUE TITLE
Update crates to Rust 2021 Edition

### ISSUE THREAD

**Issue by jregistr** [apollographql/apollo-rs#94]
## Description

Rust 2021 edition is here! Let's update the crates here to use it.

Information on migration can be found over at [The Edition Guide](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html).

Some things this effort might include:
```bash
# may need to make manual changes if errors
cargo fix --edition
```

Beyond that, update the edition in Cargo.toml to "2021".

Lastly, consider removing import statements(if available) for **TryInto**, **TryFrom** and **FromIterator** as these have been added to the prelude.

**Comment by lrlna** [comment]
@jregistr ended up doing a bit of an impromptu updated as I needed disjoin capture, so we are on 2021 edition now!
