### ISSUE TITLE
should StringValue nodes contain the quotes?

### ISSUE THREAD

**Issue by Geal** [apollographql/apollo-rs#98]
## Description

I see that when parsing a string value, the node's span contains the double quotes. Example here: https://github.com/apollographql/apollo-rs/blob/main/crates/apollo-parser/src/parser/grammar/value.rs#L208

So when manipualting it, if I want to access the text, I need to remove them. It is not a big issue, but I was wondering if that is something that could be done at the API level (a method of StringValue removing the quotes) or at the parsing level (considering the quotes bound the string token but are not part of it).

**Comment by Geal** [comment]
in which PR (and version) was it fixed? I'll check if there's still some code in the router remaining with quotes handling

**Comment by lrlna** [comment]
oops, closed without submitting a comment! apologies

we implemented a `Into<String> for StringValue` a while back as part of #111 and published way before we started doing a changelog (so pre 0.2.0). you will already have this in the router.

here's how you'd use it:

``` rust
if let ast::Value::StringValue(val) = argument.value().expect("Cannot get argument value.") {
    let val: String = val.into(); // trims `"`
}
```
